# Copa do Mundo 2026 - Análise Cartola Copa

Análise de desempenho das seleções e jogadores com dados do Cartola Copa.

In [25]:
import glob
import pandas as pd

files = sorted(glob.glob("data/pontuados-rodada-*.csv"))
dfs = []
for f in files:
    df = pd.read_csv(f)
    dfs.append(df)

df_all = pd.concat(dfs, ignore_index=True)
print(f"Total registros: {len(df_all)}")
print(f"Rodadas: {files}")
print(f"Seleções: {df_all['clube_nome'].nunique()}")
print(f"Jogadores: {df_all['atleta_id'].nunique()}")

Total registros: 2639
Rodadas: ['data/pontuados-rodada-1.csv', 'data/pontuados-rodada-2.csv', 'data/pontuados-rodada-3.csv', 'data/pontuados-rodada-4.csv']
Seleções: 48
Jogadores: 1041

## Mapa de posições

In [26]:
POSICOES = {
    1: "Goleiro",
    2: "Lateral",
    3: "Zagueiro",
    4: "Meia",
    5: "Atacante",
    6: "Técnico",
}
df_all["posicao"] = df_all["posicao_id"].map(POSICOES)

## Ranking de Seleções por Pontuação Total

Soma dos pontos de todos os jogadores que entraram em campo, por seleção.

In [27]:
em_campo = df_all[df_all["entrou_em_campo"] == True]

ranking_selecoes = (
    em_campo.groupby("clube_nome")
    .agg(
        pontuacao_total=("pontuacao", "sum"),
        media_pontuacao=("pontuacao", "mean"),
        jogadores_usados=("atleta_id", "nunique"),
        gols=("G", "sum"),
        assistencias=("A", "sum"),
        jogos=("atleta_id", "count"),
    )
    .sort_values("pontuacao_total", ascending=False)
    .round(2)
)

print("=" * 60)
print("RANKING SELEÇÕES - PONTUAÇÃO TOTAL")
print("=" * 60)
ranking_selecoes

============================================================
RANKING SELEÇÕES - PONTUAÇÃO TOTAL
============================================================

,pontuacao_total,media_pontuacao,jogadores_usados,gols,assistencias,jogos
clube_nome,,,,,,
França,447.78,6.89,22,13.0,12.0,65
Espanha,390.70,5.83,20,7.0,7.0,67
Brasil,357.98,5.34,23,9.0,8.0,67
Argentina,350.58,5.16,25,10.0,5.0,68
Inglaterra,341.94,5.10,21,8.0,7.0,67
Paraguai,322.48,4.96,23,3.0,3.0,65
Senegal,320.42,4.64,23,10.0,9.0,69
Estados Unidos,312.16,4.80,24,8.0,4.0,65
Portugal,307.01,4.58,23,7.0,4.0,67
Alemanha,302.51,4.52,24,11.0,10.0,67
Marrocos,292.62,4.37,21,7.0,6.0,67
Costa do Marfim,289.23,4.25,23,5.0,4.0,68
Bélgica,289.03,4.19,21,8.0,4.0,69
México,284.45,5.58,25,7.0,6.0,51
Holanda,269.05,3.90,23,10.0,10.0,69
Cabo Verde,264.21,3.83,22,4.0,2.0,69
Japão,260.53,3.83,25,8.0,7.0,68
Egito,240.00,3.58,22,6.0,5.0,67
Noruega,232.32,3.52,26,9.0,7.0,66
Equador,231.41,3.51,22,2.0,2.0,66
Austrália,226.68,3.54,22,2.0,1.0,64
Suécia,225.40,3.31,23,7.0,6.0,68
Irã,210.87,4.39,21,3.0,2.0,48
Argélia,205.32,3.06,23,5.0,3.0,67
Suíça,199.24,3.91,23,5.0,3.0,51
Turquia,183.18,3.59,24,3.0,2.0,51
Áustria,180.13,2.65,21,5.0,4.0,68
Curaçao,174.33,3.56,23,1.0,0.0,49
Arábia Saudita,159.71,3.13,19,1.0,0.0,51
Croácia,157.23,3.21,19,5.0,5.0,49
RD Congo,153.94,3.02,22,5.0,3.0,51
Uruguai,145.97,3.04,18,3.0,1.0,48
Jordânia,141.81,2.78,21,3.0,3.0,51
Bósnia,139.54,2.74,23,3.0,3.0,51
Tunísia,136.36,2.67,22,2.0,2.0,51
Escócia,125.58,2.46,21,1.0,0.0,51
Nova Zelândia,124.25,2.44,18,4.0,3.0,51
Canadá,121.09,3.56,19,2.0,2.0,34
Haiti,115.31,2.35,19,1.0,1.0,49
Gana,113.35,3.43,21,1.0,1.0,33
Iraque,109.63,2.15,26,1.0,1.0,51
África do Sul,105.84,3.41,19,1.0,1.0,31
Coreia do Sul,87.40,2.57,19,2.0,2.0,34
Uzbequistão,72.88,2.14,21,1.0,1.0,34
República Tcheca,71.24,2.16,20,1.0,1.0,33
Colômbia,68.62,4.04,17,0.0,0.0,17
Catar,65.01,1.91,21,1.0,1.0,34
Panamá,33.16,1.95,17,0.0,0.0,17

## Ranking de Seleções por Média de Pontuação

Média por jogador — mede qualidade técnica independente de quantos jogaram.

In [28]:
ranking_media = ranking_selecoes.sort_values("media_pontuacao", ascending=False)

print("=" * 60)
print("RANKING SELEÇÕES - MÉDIA POR JOGADOR")
print("=" * 60)
ranking_media

============================================================
RANKING SELEÇÕES - MÉDIA POR JOGADOR
============================================================

,pontuacao_total,media_pontuacao,jogadores_usados,gols,assistencias,jogos
clube_nome,,,,,,
França,447.78,6.89,22,13.0,12.0,65
Espanha,390.70,5.83,20,7.0,7.0,67
México,284.45,5.58,25,7.0,6.0,51
Brasil,357.98,5.34,23,9.0,8.0,67
Argentina,350.58,5.16,25,10.0,5.0,68
Inglaterra,341.94,5.10,21,8.0,7.0,67
Paraguai,322.48,4.96,23,3.0,3.0,65
Estados Unidos,312.16,4.80,24,8.0,4.0,65
Senegal,320.42,4.64,23,10.0,9.0,69
Portugal,307.01,4.58,23,7.0,4.0,67
Alemanha,302.51,4.52,24,11.0,10.0,67
Irã,210.87,4.39,21,3.0,2.0,48
Marrocos,292.62,4.37,21,7.0,6.0,67
Costa do Marfim,289.23,4.25,23,5.0,4.0,68
Bélgica,289.03,4.19,21,8.0,4.0,69
Colômbia,68.62,4.04,17,0.0,0.0,17
Suíça,199.24,3.91,23,5.0,3.0,51
Holanda,269.05,3.90,23,10.0,10.0,69
Japão,260.53,3.83,25,8.0,7.0,68
Cabo Verde,264.21,3.83,22,4.0,2.0,69
Turquia,183.18,3.59,24,3.0,2.0,51
Egito,240.00,3.58,22,6.0,5.0,67
Canadá,121.09,3.56,19,2.0,2.0,34
Curaçao,174.33,3.56,23,1.0,0.0,49
Austrália,226.68,3.54,22,2.0,1.0,64
Noruega,232.32,3.52,26,9.0,7.0,66
Equador,231.41,3.51,22,2.0,2.0,66
Gana,113.35,3.43,21,1.0,1.0,33
África do Sul,105.84,3.41,19,1.0,1.0,31
Suécia,225.40,3.31,23,7.0,6.0,68
Croácia,157.23,3.21,19,5.0,5.0,49
Arábia Saudita,159.71,3.13,19,1.0,0.0,51
Argélia,205.32,3.06,23,5.0,3.0,67
Uruguai,145.97,3.04,18,3.0,1.0,48
RD Congo,153.94,3.02,22,5.0,3.0,51
Jordânia,141.81,2.78,21,3.0,3.0,51
Bósnia,139.54,2.74,23,3.0,3.0,51
Tunísia,136.36,2.67,22,2.0,2.0,51
Áustria,180.13,2.65,21,5.0,4.0,68
Coreia do Sul,87.40,2.57,19,2.0,2.0,34
Escócia,125.58,2.46,21,1.0,0.0,51
Nova Zelândia,124.25,2.44,18,4.0,3.0,51
Haiti,115.31,2.35,19,1.0,1.0,49
República Tcheca,71.24,2.16,20,1.0,1.0,33
Iraque,109.63,2.15,26,1.0,1.0,51
Uzbequistão,72.88,2.14,21,1.0,1.0,34
Panamá,33.16,1.95,17,0.0,0.0,17
Catar,65.01,1.91,21,1.0,1.0,34

## Top 30 Jogadores por Pontuação Total

In [29]:
top_jogadores = (
    em_campo.groupby(["atleta_id", "apelido", "clube_nome", "posicao"])
    .agg(
        pontuacao_total=("pontuacao", "sum"),
        media_pontuacao=("pontuacao", "mean"),
        rodadas=("pontuacao", "count"),
        gols=("G", "sum"),
        assistencias=("A", "sum"),
    )
    .sort_values("pontuacao_total", ascending=False)
    .round(2)
    .head(30)
)

top_jogadores

,,,,pontuacao_total,media_pontuacao,rodadas,gols,assistencias
atleta_id,apelido,clube_nome,posicao,,,,,
95063,Mbappé,França,Atacante,78.30,19.58,4,6.0,2.0
67746,Messi,Argentina,Atacante,77.10,19.27,4,7.0,0.0
99405,Ismaïla Sarr,Senegal,Atacante,57.20,14.30,4,4.0,1.0
93334,Oyarzabal,Espanha,Atacante,56.00,14.00,4,4.0,1.0
99535,Vini Jr.,Brasil,Atacante,53.70,13.42,4,4.0,1.0
82232,Harry Kane,Inglaterra,Atacante,52.90,13.22,4,5.0,0.0
95534,Dembélé,França,Atacante,51.70,12.92,4,4.0,2.0
106032,Haaland,Noruega,Atacante,51.20,17.07,3,5.0,0.0
98019,Hakimi,Marrocos,Lateral,47.60,11.90,4,1.0,1.0
114235,Olise,França,Meia,45.10,11.27,4,0.0,5.0
110219,Bellingham,Inglaterra,Meia,44.30,11.08,4,2.0,1.0
71485,Didier Deschamps,França,Técnico,40.98,10.24,4,0.0,0.0
111019,Quiñones,México,Atacante,40.90,13.63,3,3.0,1.0
107527,Wissa,RD Congo,Atacante,39.50,13.17,3,3.0,0.0
109592,Tillman,Estados Unidos,Meia,39.20,9.80,4,1.0,1.0
108528,Galarza,Paraguai,Meia,38.90,12.97,3,1.0,1.0
102775,Rezaeian,Irã,Lateral,38.90,12.97,3,2.0,1.0
98352,Bruno Guimarães,Brasil,Meia,38.90,9.72,4,0.0,4.0
103898,Nmecha,Alemanha,Meia,38.20,9.55,4,1.0,1.0
103067,Cucurella,Espanha,Lateral,37.60,9.40,4,0.0,2.0
127435,Freeman,Estados Unidos,Lateral,36.00,9.00,4,1.0,1.0
118786,Undav,Alemanha,Atacante,35.90,8.98,4,3.0,2.0
97698,Isak,Suécia,Atacante,35.60,8.90,4,1.0,3.0
114014,Just,Nova Zelândia,Meia,35.30,11.77,3,3.0,0.0
113735,Luis de la Fuente,Espanha,Técnico,35.30,8.82,4,0.0,0.0
105267,Trossard,Bélgica,Atacante,35.20,8.80,4,2.0,1.0
81947,Laporte,Espanha,Zagueiro,35.00,8.75,4,0.0,1.0
114054,Ashour,Egito,Meia,34.70,8.68,4,2.0,0.0
105605,Matheus Cunha,Brasil,Atacante,34.70,8.67,4,3.0,0.0
67972,Cristiano Ronaldo,Portugal,Atacante,34.60,8.65,4,3.0,0.0

## Top Jogadores por Posição

In [ ]:
for pos in ["Goleiro", "Zagueiro", "Lateral", "Meia", "Atacante", "Técnico"]:
    top = (
        em_campo[em_campo["posicao"] == pos]
        .groupby(["apelido", "clube_nome"])
        .agg(
            pontuacao_total=("pontuacao", "sum"),
            gols=("G", "sum"),
            assistencias=("A", "sum"),
            SG=("SG", "sum"),
        )
        .sort_values("pontuacao_total", ascending=False)
        .round(2)
        .head(20)
    )
    print(f"\n{'=' * 50}")
    print(f"TOP 20 - {pos.upper()}")
    print(f"{'=' * 50}")
    display(top)

==================================================
TOP 20 - GOLEIRO
==================================================

                              pontuacao_total  gols  assistencias   SG
apelido      clube_nome
Gill         Paraguai                    33.8   0.0           0.0  2.0
Vozinha      Cabo Verde                  32.7   0.0           0.0  2.0
Diogo Costa  Portugal                    28.0   0.0           0.0  2.0
Unai Simón   Espanha                     27.0   0.0           0.0  4.0
Maignan      França                      25.9   0.0           0.0  2.0
Beach        Austrália                   25.2   0.0           0.0  2.0
Alisson      Brasil                      22.3   0.0           0.0  2.0
Room         Curaçao                     22.0   0.0           0.0  1.0
Tala Rangel  México                      21.5   0.0           0.0  3.0
Al-Owais     Arábia Saudita              21.3   0.0           0.0  1.0
Beiranvand   Irã                         20.7   0.0           0.0  1.0
Yahia Fofana Costa do Marfim             20.5   0.0           0.0  2.0
Zion Suzuki  Japão                       18.7   0.0           0.0  1.0
Shobeir      Egito                       18.0   0.0           0.0  0.0
Kobel        Suíça                       17.8   0.0           0.0  1.0
Freese       Estados Unidos              17.8   0.0           0.0  2.0
Pickford     Inglaterra                  16.3   0.0           0.0  2.0
Verbruggen   Holanda                     15.8   0.0           0.0  0.0
Courtois     Bélgica                     15.3   0.0           0.0  1.0
Galíndez     Equador                     14.0   0.0           0.0  1.0

==================================================
TOP 20 - ZAGUEIRO
==================================================

                                  pontuacao_total  gols  assistencias   SG
apelido           clube_nome
Laporte           Espanha                    35.0   0.0           1.0  4.0
Lisandro Martínez Argentina                  27.2   1.0           1.0  2.0
Circati           Austrália                  24.6   0.0           0.0  2.0
Junior Alonso     Paraguai                   23.9   0.0           0.0  2.0
Medina            Argentina                  23.3   0.0           1.0  2.0
Pico Lopes        Cabo Verde                 22.8   0.0           0.0  2.0
Cubarsí           Espanha                    22.2   0.0           0.0  4.0
Gabriel Magalhães Brasil                     20.7   0.0           1.0  2.0
Konsa             Inglaterra                 19.1   0.0           0.0  2.0
Pacho             Equador                    18.6   0.0           0.0  1.0
Guéhi             Inglaterra                 18.6   0.0           0.0  2.0
Van Dijk          Holanda                    18.6   1.0           1.0  0.0
Upamecano         França                     18.3   0.0           0.0  2.0
Riad              Marrocos                   18.0   0.0           1.0  1.0
Al-Amri           Arábia Saudita             17.4   1.0           0.0  1.0
Mbokazi           África do Sul              17.4   0.0           0.0  1.0
Marquinhos        Brasil                     17.3   0.0           0.0  2.0
Cuti Romero       Argentina                  17.0   0.0           0.0  2.0
Gustavo Gómez     Paraguai                   17.0   0.0           0.0  2.0
Diney Borges      Cabo Verde                 16.8   0.0           0.0  2.0

==================================================
TOP 20 - LATERAL
==================================================

                               pontuacao_total  gols  assistencias   SG
apelido        clube_nome
Hakimi         Marrocos                   47.6   1.0           1.0  1.0
Rezaeian       Irã                        38.9   2.0           1.0  1.0
Cucurella      Espanha                    37.6   0.0           2.0  4.0
Freeman        Estados Unidos             36.0   1.0           1.0  2.0
Nuno Mendes    Portugal                   28.5   1.0           0.0  2.0
Douglas Santos Brasil                     28.3   0.0           0.0  2.0
Cáceres        Paraguai                   28.1   0.0           0.0  2.0
João Cancelo   Portugal                   27.5   0.0           1.0  2.0
O'Reilly       Inglaterra                 25.0   0.0           0.0  2.0
Pedro Porro    Espanha                    24.9   1.0           0.0  2.0
Brown          Alemanha                   24.0   1.0           1.0  0.0
Aït-Nouri      Argélia                    23.5   0.0           0.0  0.0
Kimmich        Alemanha                   23.5   0.0           2.0  0.0
Llorente       Espanha                    22.4   0.0           1.0  2.0
Sidny Cabral   Cabo Verde                 22.2   1.0           0.0  1.0
Doski          Iraque                     21.6   0.0           0.0  0.0
Behich         Austrália                  20.4   0.0           0.0  2.0
Koundé         França                     19.8   0.0           0.0  2.0
Abdulhamid     Arábia Saudita             19.6   0.0           0.0  1.0
Bos            Austrália                  19.1   0.0           0.0  2.0

==================================================
TOP 20 - MEIA
==================================================

                                pontuacao_total  gols  assistencias   SG
apelido         clube_nome
Olise           França                     45.1   0.0           5.0  0.0
Bellingham      Inglaterra                 44.3   2.0           1.0  0.0
Tillman         Estados Unidos             39.2   1.0           1.0  0.0
Galarza         Paraguai                   38.9   1.0           1.0  0.0
Bruno Guimarães Brasil                     38.9   0.0           4.0  0.0
Nmecha          Alemanha                   38.2   1.0           1.0  0.0
Just            Nova Zelândia              35.3   3.0           0.0  0.0
Ashour          Egito                      34.7   2.0           0.0  0.0
Saibari         Marrocos                   33.5   3.0           0.0  0.0
Tielemans       Bélgica                    31.8   2.0           0.0  0.0
Elliot Anderson Inglaterra                 30.8   0.0           1.0  0.0
Enciso          Paraguai                   30.8   1.0           2.0  0.0
Maxi Araújo     Uruguai                    29.8   2.0           1.0  0.0
Wirtz           Alemanha                   29.5   0.0           3.0  0.0
Tchouaméni      França                     29.4   0.0           1.0  0.0
Ödegaard        Noruega                    28.9   0.0           3.0  0.0
Ayari           Suécia                     28.9   2.0           0.0  0.0
El Aynaoui      Marrocos                   28.3   0.0           0.0  0.0
Hannibal        Tunísia                    27.8   0.0           2.0  0.0
Pape Gueye      Senegal                    27.1   2.0           1.0  0.0

==================================================
TOP 20 - ATACANTE
==================================================

                              pontuacao_total  gols  assistencias   SG
apelido           clube_nome
Mbappé            França                 78.3   6.0           2.0  0.0
Messi             Argentina              77.1   7.0           0.0  0.0
Ismaïla Sarr      Senegal                57.2   4.0           1.0  0.0
Oyarzabal         Espanha                56.0   4.0           1.0  0.0
Vini Jr.          Brasil                 53.7   4.0           1.0  0.0
Harry Kane        Inglaterra             52.9   5.0           0.0  0.0
Dembélé           França                 51.7   4.0           2.0  0.0
Haaland           Noruega                51.2   5.0           0.0  0.0
Quiñones          México                 40.9   3.0           1.0  0.0
Wissa             RD Congo               39.5   3.0           0.0  0.0
Undav             Alemanha               35.9   3.0           2.0  0.0
Isak              Suécia                 35.6   1.0           3.0  0.0
Trossard          Bélgica                35.2   2.0           1.0  0.0
Matheus Cunha     Brasil                 34.7   3.0           0.0  0.0
Cristiano Ronaldo Portugal               34.6   3.0           0.0  0.0
Gakpo             Holanda                34.0   3.0           1.0  0.0
Havertz           Alemanha               33.4   3.0           0.0  0.0
Barcola           França                 33.1   2.0           1.0  0.0
Summerville       Holanda                32.8   2.0           2.0  0.0
Plata             Equador                32.7   1.0           0.0  0.0

==================================================
TOP 20 - TÉCNICO
==================================================

                                     pontuacao_total  gols  assistencias   SG
apelido             clube_nome
Didier Deschamps    França                     40.98   0.0           0.0  0.0
Luis de la Fuente   Espanha                    35.30   0.0           0.0  0.0
Lionel Scaloni      Argentina                  32.88   0.0           0.0  0.0
Carlo Ancelotti     Brasil                     32.58   0.0           0.0  0.0
Thomas Tuchel       Inglaterra                 31.24   0.0           0.0  0.0
Mauricio Pochettino Estados Unidos             28.76   0.0           0.0  0.0
Gustavo Alfaro      Paraguai                   28.08   0.0           0.0  0.0
Pape Thiaw          Senegal                    27.62   0.0           0.0  0.0
Roberto Martínez    Portugal                   27.41   0.0           0.0  0.0
Julian Nagelsmann   Alemanha                   27.11   0.0           0.0  0.0
Javier Aguirre      México                     26.45   0.0           0.0  0.0
Mohamed Ouahbi      Marrocos                   26.22   0.0           0.0  0.0
Emerse Faé          Costa do Marfim            25.93   0.0           0.0  0.0
Rudi Garcia         Bélgica                    25.93   0.0           0.0  0.0
Ronald Koeman       Holanda                    24.25   0.0           0.0  0.0
Hajime Moriyasu     Japão                      22.63   0.0           0.0  0.0
Staale Solbakken    Noruega                    22.12   0.0           0.0  0.0
Bubista             Cabo Verde                 22.01   0.0           0.0  0.0
Hossam Hassan       Egito                      20.90   0.0           0.0  0.0
Sebastián Beccacece Equador                    20.21   0.0           0.0  0.0

## Scouts Agregados por Seleção

Perfil técnico: gols, assistências, desarmes, finalizações, faltas.

In [31]:
scout_cols = ["G", "A", "FT", "FD", "FF", "FS", "FC", "DE", "DS", "SG", "CA", "CV", "GC", "GS"]
available = [c for c in scout_cols if c in em_campo.columns]

scout_labels = {
    "G": "Gols", "A": "Assistências", "FT": "Finalizações Certas",
    "FD": "Finalizações Defendidas", "FF": "Finalizações Fora",
    "FS": "Faltas Sofridas", "FC": "Faltas Cometidas",
    "DE": "Desarmes", "DS": "Dribles", "SG": "Saldo de Gols (DEF)",
    "CA": "Cartões Amarelos", "CV": "Cartões Vermelhos",
    "GC": "Gols Contra", "GS": "Gols Sofridos (GOL)",
}

perfil = (
    em_campo.groupby("clube_nome")[available]
    .sum()
    .fillna(0)
    .astype(int)
    .sort_values("G", ascending=False)
)
perfil.columns = [scout_labels.get(c, c) for c in perfil.columns]

print("PERFIL TÉCNICO POR SELEÇÃO")
perfil.head(20)

PERFIL TÉCNICO POR SELEÇÃO

,Gols,Assistências,Finalizações Certas,Finalizações Defendidas,Finalizações Fora,Faltas Sofridas,Faltas Cometidas,Desarmes,Dribles,Saldo de Gols (DEF),Cartões Amarelos,Cartões Vermelhos,Gols Contra,Gols Sofridos (GOL)
clube_nome,,,,,,,,,,,,,,
França,13,12,4,20,23,30,36,8,71,13,1,0,0,2
Alemanha,11,10,1,17,24,40,47,6,59,0,3,0,0,5
Senegal,10,9,4,13,27,49,35,12,52,5,3,0,0,9
Argentina,10,5,2,15,17,41,45,4,68,14,3,0,0,3
Holanda,10,10,1,12,12,43,44,16,45,0,3,0,0,5
Brasil,9,8,1,16,20,48,44,11,70,11,7,0,0,2
Noruega,9,7,1,12,13,27,42,11,49,0,2,0,0,8
Estados Unidos,8,4,2,9,17,58,44,6,59,14,5,1,0,4
Japão,8,7,0,6,13,30,55,14,56,6,4,0,0,5
Bélgica,8,4,2,16,34,44,50,11,54,7,4,1,0,4
Inglaterra,8,7,1,23,24,62,46,6,55,12,3,0,0,3
Suécia,7,6,1,16,16,49,42,14,47,0,5,0,0,10
Portugal,7,4,1,7,24,46,34,15,55,13,5,0,0,2
México,7,6,1,6,18,34,35,5,33,18,2,1,0,0
Marrocos,7,6,2,20,14,59,46,7,66,5,2,0,1,4
Espanha,7,7,4,19,30,30,42,5,63,21,2,0,0,0
Egito,6,5,0,13,25,53,47,10,65,0,8,0,2,4
Suíça,5,3,0,13,12,36,40,11,41,5,2,0,1,2
Argélia,5,3,1,10,14,39,29,9,64,0,3,0,0,9
RD Congo,5,3,1,3,20,32,26,6,37,0,5,0,0,4

## Evolução por Rodada

In [32]:
rodada_col = [c for c in df_all.columns if 'rodada' in c.lower()]
if not rodada_col:
    df_all["rodada"] = df_all.groupby("atleta_id").cumcount() + 1
    rodada_col = ["rodada"]

# Infer rodada from file order
dfs_labeled = []
for i, f in enumerate(files, 1):
    df_temp = pd.read_csv(f)
    df_temp["rodada"] = i
    dfs_labeled.append(df_temp)

df_rodadas = pd.concat(dfs_labeled, ignore_index=True)
df_rodadas["posicao"] = df_rodadas["posicao_id"].map(POSICOES)
em_campo_r = df_rodadas[df_rodadas["entrou_em_campo"] == True]

evolucao = (
    em_campo_r.groupby(["rodada", "clube_nome"])
    .agg(pontuacao_total=("pontuacao", "sum"))
    .reset_index()
    .pivot(index="clube_nome", columns="rodada", values="pontuacao_total")
    .fillna(0)
)
evolucao["total"] = evolucao.sum(axis=1)
evolucao = evolucao.sort_values("total", ascending=False)

print("PONTUAÇÃO POR RODADA")
evolucao.head(20)

PONTUAÇÃO POR RODADA

rodada                1       2       3       4   total
clube_nome
França            74.42  122.20  119.91  131.25  447.78
Espanha           74.18  113.25   77.47  125.80  390.70
Brasil            52.25  104.09  124.49   77.15  357.98
Argentina        120.89   89.04   61.65   79.00  350.58
Inglaterra        94.27   71.56  113.47   62.64  341.94
Paraguai          39.71   96.78  101.89   84.10  322.48
Senegal           46.69   66.76  142.93   64.04  320.42
Estados Unidos    75.95   99.40   49.85   86.96  312.16
Portugal          37.09  124.05   79.42   66.45  307.01
Alemanha         138.67   71.80   47.13   44.91  302.51
Marrocos          65.35   71.58   97.33   58.36  292.62
Costa do Marfim   80.09   48.11   97.98   63.05  289.23
Bélgica           44.29   67.75  104.64   72.35  289.03
México            82.49    0.00  106.27   95.69  284.45
Holanda           47.45  106.71   68.53   46.36  269.05
Cabo Verde        76.58   52.47   70.25   64.91  264.21
Japão             55.20  121.22   56.40   27.71  260.53
Egito             57.60  102.13   41.35   38.92  240.00
Noruega           55.22   64.93   48.22   63.95  232.32
Equador           58.15   85.64   68.09   19.53  231.41

## Jogos por Diferença — Média Ajustada por Adversário + Ranking FIFA (Quartas de Final)

Média Cartola ajustada pela força do adversário (regressão linear: pontuação ~ ranking FIFA do oponente). Times que pontuaram bem contra adversários fortes sobem; times que só pontuaram contra fracos descem.

In [ ]:
import numpy as np

ranking_fifa = pd.read_csv("data/fifa_ranking.csv")
partidas = pd.read_csv("data/partidas.csv")

# Per-team per-rodada mean pontuação
team_rodada = (
    em_campo_r.groupby(["clube_nome", "rodada"])["pontuacao"]
    .mean()
    .reset_index()
    .rename(columns={"pontuacao": "media_rodada"})
)

# Build opponent mapping from partidas
opp_rows = []
for _, p in partidas.iterrows():
    opp_rows.append({"clube_nome": p["mandante"], "rodada": p["rodada"], "adversario": p["visitante"]})
    opp_rows.append({"clube_nome": p["visitante"], "rodada": p["rodada"], "adversario": p["mandante"]})
opponents = pd.DataFrame(opp_rows)

# Merge opponent + opponent FIFA ranking
team_rodada = team_rodada.merge(opponents, on=["clube_nome", "rodada"], how="left")
team_rodada = team_rodada.merge(
    ranking_fifa.rename(columns={"clube_nome": "adversario", "fifa_ranking": "adv_rank"}),
    on="adversario", how="left",
)
team_rodada = team_rodada.dropna(subset=["adv_rank", "media_rodada"])

# Linear regression: media_rodada ~ adv_rank
x = team_rodada["adv_rank"].values
y = team_rodada["media_rodada"].values
slope, intercept = np.polyfit(x, y, 1)

team_rodada["predicted"] = intercept + slope * team_rodada["adv_rank"]
team_rodada["residual"] = team_rodada["media_rodada"] - team_rodada["predicted"]

overall_mean = y.mean()

print(f"Regressão: média = {intercept:.3f} + {slope:.4f} × rank_adversário")
print(f"Média geral: {overall_mean:.2f}")
print(f"Interpretação: cada posição mais fraca do adversário no ranking FIFA vale {slope:.4f} pts na média\n")

# Adjusted mean = overall_mean + mean(residuals per team)
adjusted = (
    team_rodada.groupby("clube_nome")["residual"]
    .mean()
    .reset_index()
    .rename(columns={"residual": "adj_residual"})
)
adjusted["media_ajustada"] = (overall_mean + adjusted["adj_residual"]).round(2)

pontuacao_selecao = adjusted[["clube_nome", "media_ajustada"]]

print("TOP 15 — MÉDIA AJUSTADA POR ADVERSÁRIO")
print("=" * 50)
display(adjusted[["clube_nome", "media_ajustada"]].sort_values("media_ajustada", ascending=False).head(15).reset_index(drop=True))

def confrontos_por_rodada(partidas_df, pontuacao_df, ranking_df, rodada):
    rodada_df = partidas_df[partidas_df["rodada"] == rodada].copy()

    rodada_df = rodada_df.merge(
        pontuacao_df.rename(columns={"clube_nome": "mandante", "media_ajustada": "adj_1"}),
        on="mandante", how="left",
    )
    rodada_df = rodada_df.merge(
        pontuacao_df.rename(columns={"clube_nome": "visitante", "media_ajustada": "adj_2"}),
        on="visitante", how="left",
    )

    rodada_df = rodada_df.merge(
        ranking_df.rename(columns={"clube_nome": "mandante", "fifa_ranking": "fifa_rank_1"})[["mandante", "fifa_rank_1"]],
        on="mandante", how="left",
    )
    rodada_df = rodada_df.merge(
        ranking_df.rename(columns={"clube_nome": "visitante", "fifa_ranking": "fifa_rank_2"})[["visitante", "fifa_rank_2"]],
        on="visitante", how="left",
    )

    rodada_df["adj_1"] = rodada_df["adj_1"].fillna(0).round(2)
    rodada_df["adj_2"] = rodada_df["adj_2"].fillna(0).round(2)
    rodada_df["diff_adj"] = abs(rodada_df["adj_1"] - rodada_df["adj_2"]).round(2)
    rodada_df["diff_fifa"] = abs(rodada_df["fifa_rank_1"] - rodada_df["fifa_rank_2"])

    rodada_df["favorito_cartola"] = rodada_df.apply(
        lambda r: r["mandante"] if r["adj_1"] > r["adj_2"] else r["visitante"], axis=1
    )
    rodada_df["adj_favorito"] = rodada_df[["adj_1", "adj_2"]].max(axis=1)
    rodada_df["azarão_cartola"] = rodada_df.apply(
        lambda r: r["visitante"] if r["adj_1"] > r["adj_2"] else r["mandante"], axis=1
    )
    rodada_df["adj_azarão"] = rodada_df[["adj_1", "adj_2"]].min(axis=1)

    rodada_df["favorito_fifa"] = rodada_df.apply(
        lambda r: r["mandante"] if r["fifa_rank_1"] < r["fifa_rank_2"] else r["visitante"], axis=1
    )
    rodada_df["rank_favorito"] = rodada_df[["fifa_rank_1", "fifa_rank_2"]].min(axis=1).astype(int)
    rodada_df["rank_azarão"] = rodada_df[["fifa_rank_1", "fifa_rank_2"]].max(axis=1).astype(int)

    cols = [
        "favorito_cartola", "adj_favorito", "azarão_cartola", "adj_azarão", "diff_adj",
        "favorito_fifa", "rank_favorito", "rank_azarão", "diff_fifa", "data",
    ]
    return rodada_df[cols].sort_values("diff_adj", ascending=False).reset_index(drop=True)

print("\nRODADA 5 (QUARTAS DE FINAL) — MÉDIA AJUSTADA + RANKING FIFA")
print("=" * 70)
display(confrontos_por_rodada(partidas, pontuacao_selecao, ranking_fifa, 5))

## Análise da Minha Escalação — Rodada 5 (Quartas de Final)

In [ ]:
TITULARES = [
    {"apelido": "Maignan", "posicao": "Goleiro", "selecao": "França", "preco": 11.76},
    {"apelido": "Hakimi", "posicao": "Lateral", "selecao": "Marrocos", "preco": 17.72},
    {"apelido": "Medina", "posicao": "Zagueiro", "selecao": "Argentina", "preco": 8.37},
    {"apelido": "Laporte", "posicao": "Zagueiro", "selecao": "Espanha", "preco": 10.82},
    {"apelido": "Jorge Sánchez", "posicao": "Lateral", "selecao": "México", "preco": 9.24},
    {"apelido": "Bruno Guimarães", "posicao": "Meia", "selecao": "Brasil", "preco": 13.06},
    {"apelido": "Olise", "posicao": "Meia", "selecao": "França", "preco": 21.69},
    {"apelido": "Galarza", "posicao": "Meia", "selecao": "Paraguai", "preco": 11.02},
    {"apelido": "Messi", "posicao": "Atacante", "selecao": "Argentina", "preco": 26.00, "capitao": True},
    {"apelido": "Mbappé", "posicao": "Atacante", "selecao": "França", "preco": 27.90},
    {"apelido": "Vini Jr.", "posicao": "Atacante", "selecao": "Brasil", "preco": 21.83},
]

BANCO = [
    {"apelido": "Gill", "posicao": "Goleiro", "selecao": "Paraguai", "preco": 7.77},
    {"apelido": "Cáceres", "posicao": "Lateral", "selecao": "Paraguai", "preco": 8.15},
    {"apelido": "Diop", "posicao": "Zagueiro", "selecao": "Marrocos", "preco": 5.43},
    {"apelido": "Saibari", "posicao": "Meia", "selecao": "Marrocos", "preco": 10.43},
    {"apelido": "Quiñones", "posicao": "Atacante", "selecao": "México", "preco": 14.67},
]

TECNICO = {"apelido": "Lionel Scaloni", "selecao": "Argentina", "preco": 12.61}

RODADA = 5


def get_adversario(selecao, rodada=RODADA):
    r = partidas[partidas["rodada"] == rodada]
    m = r[(r["mandante"] == selecao) | (r["visitante"] == selecao)]
    if m.empty:
        return "—"
    row = m.iloc[0]
    return row["visitante"] if row["mandante"] == selecao else row["mandante"]


def get_rank(selecao):
    r = ranking_fifa[ranking_fifa["clube_nome"] == selecao]
    return int(r["fifa_ranking"].values[0]) if len(r) > 0 else None


def get_historico(apelido, selecao=None):
    mask = em_campo["apelido"].str.contains(apelido, case=False, na=False)
    if selecao:
        mask = mask & (em_campo["clube_nome"] == selecao)
    jogador = em_campo[mask]
    if jogador.empty:
        return {"pts_total": 0, "media": 0, "gols": 0, "assists": 0}
    return {
        "pts_total": round(jogador["pontuacao"].sum(), 2),
        "media": round(jogador["pontuacao"].mean(), 2),
        "gols": int(jogador["G"].sum()),
        "assists": int(jogador["A"].sum()),
    }


def get_media_ajustada(selecao):
    r = pontuacao_selecao[pontuacao_selecao["clube_nome"] == selecao]
    return round(r["media_ajustada"].values[0], 2) if len(r) > 0 else None


rows = []
for p in TITULARES + BANCO:
    h = get_historico(p["apelido"], p["selecao"])
    adv = get_adversario(p["selecao"])
    tr = get_rank(p["selecao"])
    ar = get_rank(adv) if adv != "—" else None
    diff = (ar - tr) if tr and ar else None
    adj = get_media_ajustada(p["selecao"])
    rows.append({
        "jogador": p["apelido"],
        "posicao": p["posicao"],
        "selecao": p["selecao"],
        "fifa_rank": tr,
        "adversario": adv,
        "adv_rank": ar,
        "diff_rank": diff,
        "media_cartola": h["media"],
        "pts_total": h["pts_total"],
        "gols": h["gols"],
        "assists": h["assists"],
        "preco": p["preco"],
        "media_adj_selecao": adj,
        "titular": p in TITULARES,
        "capitao": p.get("capitao", False),
    })

df_esc = pd.DataFrame(rows)

print("TITULARES")
print("=" * 80)
display(df_esc[df_esc["titular"]][
    ["jogador", "posicao", "selecao", "fifa_rank", "adversario", "adv_rank", "diff_rank",
     "media_cartola", "pts_total", "gols", "assists", "media_adj_selecao", "capitao"]
])

print("\nBANCO")
print("=" * 80)
display(df_esc[~df_esc["titular"]][
    ["jogador", "posicao", "selecao", "fifa_rank", "adversario", "adv_rank", "diff_rank",
     "media_cartola", "pts_total", "media_adj_selecao"]
])

In [ ]:
selecoes_usadas = df_esc["selecao"].unique()
custo_tit = sum(p["preco"] for p in TITULARES)
custo_banco = sum(p["preco"] for p in BANCO)
custo_total = custo_tit + custo_banco + TECNICO["preco"]

print("RESUMO DA ESCALAÇÃO")
print("=" * 70)
print(f"  Formação: 4-3-3")
print(f"  Seleções: {len(selecoes_usadas)} diferentes")
print(f"  Capitão: Messi (pontua em dobro)")
print(f"  Técnico: {TECNICO['apelido']} ({TECNICO['selecao']})")
print(f"  Custo: C$ {custo_total:.2f} (titulares: {custo_tit:.2f} | banco: {custo_banco:.2f} | técnico: {TECNICO['preco']:.2f})")

print(f"\nANÁLISE DE RISCO POR CONFRONTO")
print("=" * 70)
confrontos = {}
all_players = TITULARES + BANCO + [TECNICO]
for p in all_players:
    adv = get_adversario(p["selecao"])
    key = f"{p['selecao']} vs {adv}"
    if key not in confrontos:
        tr = get_rank(p["selecao"])
        ar = get_rank(adv) if adv != "—" else None
        adj = get_media_ajustada(p["selecao"])
        confrontos[key] = {"jogadores": [], "team_rank": tr, "adv_rank": ar, "media_adj": adj}
    confrontos[key]["jogadores"].append(p["apelido"])

for conf, info in sorted(confrontos.items(), key=lambda x: len(x[1]["jogadores"]), reverse=True):
    n = len(info["jogadores"])
    tr, ar = info["team_rank"], info["adv_rank"]
    adj = info["media_adj"]
    try:
        diff = int(ar) - int(tr)
        risk = "BAIXO" if diff > 20 else "MÉDIO" if diff > 0 else "ALTO"
    except (ValueError, TypeError):
        risk = "?"
    adj_str = f" | média adj: {adj}" if adj else ""
    print(f"\n  {conf} (#{tr} vs #{ar}) — Risco: {risk}{adj_str}")
    print(f"    Jogadores: {', '.join(info['jogadores'])} ({n})")
    if n >= 3:
        print(f"    *** {n} jogadores no mesmo jogo — alta concentração")